nnoremap <Leader>sh :setlocal hlsearch!<Return>
nnoremap <Leader>sl :setlocal list!<Return>
nnoremap <Leader>sn :setlocal number!<Return>
nnoremap <Leader>sN :setlocal relativenumber!<Return>
nnoremap <Leader>sp :setlocal paste!<Return>
nnoremap <Leader>ss :setlocal spell!<Return>
nnoremap <Leader>sz :setlocal foldenable!<Return>
nnoremap <Leader>sc :setlocal cursorcolumn!<Return>
nnoremap <Leader>sC :setlocal cursorline!<Return>
nnoremap <Leader>sw :setlocal wrap!<Return>
